<a href="https://colab.research.google.com/github/Adithya759/Adithya/blob/main/Assessment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **#Numpy Assessment**

In [ ]:
#1
import numpy as np
arr = np.arange(10, 50)
print("Original array:\n", arr)


reshaped = arr.reshape(4, 10)
print("\nReshaped 4x10 matrix:\n", reshaped)


last_col = reshaped[:, -1]
print("\nLast column:\n", last_col)

Original array:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

Reshaped 4x10 matrix:
 [[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]

Last column:
 [19 29 39 49]


In [ ]:
#2
import numpy as np

matrix_5s = np.full((3, 3), 5)

matrix_1_to_9 = np.arange(1, 10).reshape(3, 3)

print("Matrix of 5s:\n", matrix_5s)
print("\nMatrix with values from 1 to 9:\n", matrix_1_to_9)


added = matrix_5s + matrix_1_to_9
print("\nAdded Matrix:\n", added)


multiplied = matrix_5s * matrix_1_to_9
print("\nElement-wise Multiplied Matrix:\n", multiplied)


transpose_result = multiplied.T
print("\nTranspose of the Multiplied Matrix:\n", transpose_result)

Matrix of 5s:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]

Matrix with values from 1 to 9:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Added Matrix:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

Element-wise Multiplied Matrix:
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]

Transpose of the Multiplied Matrix:
 [[ 5 20 35]
 [10 25 40]
 [15 30 45]]


In [ ]:
#3
import numpy as np

arr = np.random.randint(10, 101, size=15)
print("Original array:\n", arr)

replaced = arr > 50
arr[replaced] = -1
print("\nModified array (values > 50 replaced with -1):\n", arr)

count_replaced = np.sum(replaced)
print("\nNumber of values replaced:", count_replaced)

Original array:
 [92 17 79 80 75 30 77 81 87 10 79 50 77 59 10]

Modified array (values > 50 replaced with -1):
 [-1 17 -1 -1 -1 30 -1 -1 -1 10 -1 50 -1 -1 10]

Number of values replaced: 10


In [ ]:
#4
import numpy as np

arr = np.random.rand(5, 4)
print("Original 5x4 array:\n", arr)

row_sums = arr.sum(axis=1)
max_row_index = np.argmax(row_sums)
print("\nRow with maximum sum (index {}):\n".format(max_row_index), arr[max_row_index])


normalized_arr = np.zeros_like(arr)
for i in range(arr.shape[0]):
    row_min = arr[i].min()
    row_max = arr[i].max()
    if row_max != row_min:
        normalized_arr[i] = (arr[i] - row_min) / (row_max - row_min)
    else:
        normalized_arr[i] = 0
print("\nNormalized array (row-wise min-max):\n", normalized_arr)


Original 5x4 array:
 [[7.52207710e-01 1.18991051e-01 8.17271797e-01 7.62800209e-01]
 [7.51525758e-01 1.56755164e-01 5.39593694e-02 5.54161674e-02]
 [5.27606185e-04 8.69002490e-02 6.58420660e-01 1.70678280e-01]
 [8.00498021e-01 1.19723816e-01 7.31798790e-02 3.85007117e-02]
 [6.34261385e-01 7.96130454e-01 6.63798680e-02 8.38135667e-01]]

Row with maximum sum (index 0):
 [0.75220771 0.11899105 0.8172718  0.76280021]

Normalized array (row-wise min-max):
 [[0.90682245 0.         1.         0.92199185]
 [1.         0.14736346 0.         0.0020884 ]
 [0.         0.13128675 1.         0.25862969]
 [1.         0.10659238 0.04551088 0.        ]
 [0.73583058 0.94557189 0.         1.        ]]


In [ ]:
#5
import numpy as np

arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])

unique_elements = np.unique(arr)
print("Unique elements:", unique_elements)

elements, counts = np.unique(arr, return_counts=True)
duplicates = elements[counts > 1]
print("Duplicate elements:", duplicates)


Unique elements: [1 3 5 7 9]
Duplicate elements: [1 3 5]


In [ ]:
#6
import numpy as np

arr = np.arange(1, 37).reshape(6, 6)
print("Original 6x6 array:\n", arr)

submatrix = arr[1:5, 1:5]
print("\nMiddle 4x4 submatrix:\n", submatrix)

even_numbers = submatrix[submatrix % 2 == 0]
print("\nEven numbers in the submatrix:\n", even_numbers)


Original 6x6 array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Middle 4x4 submatrix:
 [[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]

Even numbers in the submatrix:
 [ 8 10 14 16 20 22 26 28]


In [ ]:
#7
import numpy as np

arr = np.arange(12).reshape(3, 4)
print("Original (3,4) array:\n", arr)

reshaped_2x6 = arr.reshape(2, 6)
print("\nReshaped to (2,6):\n", reshaped_2x6)

flattened = reshaped_2x6.flatten()
print("\nFlattened 1D array:\n", flattened)

reshaped_4x3 = flattened.reshape(4, 3)
print("\nReshaped back to (4,3):\n", reshaped_4x3)


Original (3,4) array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped to (2,6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Flattened 1D array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped back to (4,3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
#8
import numpy as np

a = np.array([[1, 2], [3, 4]])
print("Original array:\n", a)

new_row = np.array([[5, 6]])
a = np.vstack([a, new_row])
print("\nAfter appending new row:\n", a)

new_col = np.array([[7], [8], [9]])
a = np.hstack([a, new_col])
print("\nAfter appending new column:\n", a)


Original array:
 [[1 2]
 [3 4]]

After appending new row:
 [[1 2]
 [3 4]
 [5 6]]

After appending new column:
 [[1 2 7]
 [3 4 8]
 [5 6 9]]


In [ ]:
#9
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

joined = np.concatenate((a, b, c))
print("Joined array:\n", joined)

matrix = joined.reshape(3, 3)
print("\nReshaped 3x3 matrix:\n", matrix)

diagonal = np.diag(matrix)
print("\nDiagonal elements:\n", diagonal)


Joined array:
 [1 2 3 4 5 6 7 8 9]

Reshaped 3x3 matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Diagonal elements:
 [1 5 9]


In [ ]:
#10
import numpy as np

arr = np.arange(1, 21)
print("Original array:\n", arr)

div_by_3_or_5 = arr[(arr % 3 == 0) | (arr % 5 == 0)]
print("\nValues divisible by 3 or 5:\n", div_by_3_or_5)

count = div_by_3_or_5.size
print("\nCount of values divisible by 3 or 5:", count)


Original array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Values divisible by 3 or 5:
 [ 3  5  6  9 10 12 15 18 20]

Count of values divisible by 3 or 5: 9


#Pandas Assessment


In [ ]:
#1
def range(a):
  maximum=max(a)
  minimum=min(a)
  return maximum,minimum

a=[2,4,5,13,4,9]
maximum,minimum = range(a)
print("Range = ",maximum,minimum)

Range =  13 2


In [ ]:
#2
def mean_value(numbers):
  if not numbers:
    return None
  total = sum(numbers)
  mean = total / len(numbers)
  return mean
numbers=[2,43,67,8]
mean = mean_value(numbers)
print("Mean value = ",mean)

Mean value =  30.0


In [ ]:
#3
def median_value(num):
  if not numbers:
    return None
  x = sorted(num)
  l = len(num)
  if l%2==0:
   median=(num[l//2]+num[l//2])/2
  else:
   median=num[l//2]
  return median
num=[2,3,5,6,7,9]
median=median_value(num)
print("Median:",median)

Median: 6.0


In [ ]:
#5
def percentile_value(p):
    x = sorted(p)
    n = len(x)
    perc = 90 / 100 * (n - 1)
    y = int(perc)
    fraction = perc - y

    if y + 1 < n:
        m = x[y] + fraction * (x[y + 1] - x[y])


    return perc, y, m

x = [10, 20, 30, 40, 50]
perc, y, m = percentile_value(x)
print("Percentile position (float):", perc)
print("Lower index used:", y)
print("Interpolated 90th Percentile value:", m)


Percentile position (float): 3.6
Lower index used: 3
Interpolated 90th Percentile value: 46.0


In [ ]:
#6
def lower_bound(a):
  a.sort()
  n=len(a)
  Q1 =int (25/100)*(n-1)
  Q3 = int (75/100)*(n-1)
  IQR = a[Q3]-a[Q1]
  LB = a[Q1]-1.5*IQR
  return LB
a=[10,20,30,40,50]
LB = lower_bound(a)
print("LB:",LB)

LB: 10.0


In [ ]:
#7
def outliers(a):
    a = sorted(a)
    n = len(a)

    Q1_index = int(0.25 * (n - 1))
    Q3_index = int(0.75 * (n - 1))

    Q1 = a[Q1_index]
    Q3 = a[Q3_index]
    IQR = Q3 - Q1
    LB = Q1 - 1.5 * IQR
    UB = Q3 + 1.5 * IQR
    return [x for x in a if x < LB or x > UB]
a = [10, 20, 30, 40, 50, 100]
print("Outliers:", outliers(a))


Outliers: [100]


In [ ]:
#8
def standard_deviation(a):
  a.sort
  b=len(a)
  mean=(sum(a)/b)
  c=sum((x-mean)**2 for x in a)/(b-1)
# d=c/z-1
# print("Variance:",c)
  sd = c**0.5
  return sd
a=[10,20,30,40,50]
sd=standard_deviation(a)
print("Standard Deviation:",sd)

Standard Deviation: 15.811388300841896


In [ ]:
#9
def z_score(a):
  mean=sum(a)/len(a)
  sd=standard_deviation(a)
  z=[(x-mean)/sd for x in a]
  return z
a=[10,20,30,40,50]
z=z_score(a)
print("Z-score:",z)


Z-score: [-1.2649110640673518, -0.6324555320336759, 0.0, 0.6324555320336759, 1.2649110640673518]
